{
 "title": "Container Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {
     "query": "label_values(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\",namespace=~\"weather-app|monitoring\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Wise CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (\nrate(container_cpu_usage_seconds_total{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\",cpu=\"total\"\n}[2m]) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Container Wise Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (container) (\n(\ncontainer_memory_working_set_bytes{container=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\"}\n/\ncontainer_spec_memory_limit_bytes{container=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\"}\n) * 100\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU Utilization in Cores",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})",
     "legendFormat": "Total CPU's"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Total Used CPU's"
    },
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})\n-\nsum(rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m]))",
     "legendFormat": "Total Available CPU's"
    }
   ]
  },
  {
   "title": "Total System Level Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Total RAM (GB)"
    },
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "Available RAM (GB)"
    },
    {
     "expr": "(\nnode_memory_MemTotal_bytes - node_memory_MemAvailable_bytes\n) / 1024 / 1024 / 1024",
     "legendFormat": "Used Memory (GB)"
    },
    {
     "expr": "(\n(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)\n/\nnode_memory_MemTotal_bytes\n) * 100",
     "legendFormat": "Memory Usage %"
    }
   ]
  },
  {
   "title": "Total CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{mode=\"system\"})",
     "legendFormat": "Total CPU's"
    },
    {
     "expr": "(\nsum(rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m]))\n/\ncount(node_cpu_seconds_total{mode=\"system\"})\n) * 100",
     "legendFormat": "Total Used CPU's %"
    },
    {
     "expr": "100 - (\nsum(rate(container_cpu_usage_seconds_total{container!=\"\",container!=\"POD\"}[1m]))\n/\ncount(node_cpu_seconds_total{mode=\"system\"})\n) * 100",
     "legendFormat": "Toal Available CPU's %"
    }
   ]
  },
  {
   "title": "Container Wise Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\"\n} / 1024 / 1024",
     "legendFormat": "Used Memory (MB)"
    },
    {
     "expr": "container_spec_memory_limit_bytes{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\"\n} / 1024 / 1024",
     "legendFormat": "Memory Limit (MB)"
    },
    {
     "expr": "(\ncontainer_spec_memory_limit_bytes{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\"\n}\n-\ncontainer_memory_working_set_bytes{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\"\n}\n) / 1024 / 1024",
     "legendFormat": "Remaining Memory (MB)"
    }
   ]
  },
  {
   "title": "Container wise Used CPU & Remaining CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\",cpu=\"total\"\n}[2m]) * 100",
     "legendFormat": "Total CPU Used %"
    },
    {
     "expr": "100 - (\nsum(\nrate(container_cpu_usage_seconds_total{\ncontainer=~\"$container\",container!=\"POD\",container!=\"\",namespace=~\"weather-app|monitoring\",cpu=\"total\"\n}[2m])\n)\n/\ncount(node_cpu_seconds_total{mode=\"idle\"})\n) * 100",
     "legendFormat": "Total CPU's Available %"
    }
   ]
  }
 ]
}
{
 "title": "Logs  Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Container Wise Logs Monitoring",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=~\"$container\"}"
    }
   ]
  }
 ]
}